# Generated by Django 3.0.4 on 2020-03-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
