# Generated by Django 3.0.4 on 2020-03-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20200321_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Genre',
            new_name='GameGenre',
        ),
    ]
